name: Build and Publish
on: [workflow_dispatch, push]
concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Ruby: Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Jekyll build
        run: bundle exec jekyll build --trace --profile
      - name: Publish to gh-pages branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          enable_jekyll: false
